### PR TITLE
Added support for multiple listening ports and made winston accessible

### PR DESCRIPTION
**Pull request by PaulFreund**
- Added support for multiple listening ports
- Made winston accessible from outside

I tried to follow your coding style, I hope I didn't miss something. Using the server from an application and not as standalone. Very good work, thank you!

### CODE REVIEW

**Comment by jrasanen** [comment]
This pull request has conflicts and should be rebased with the master

**Comment by AlMcKinlay** [comment]
@PaulFreund I've forked the project and planning on deploying it on npm, as it looks like this project is dead.. Do you want to add this PR to my repo as well? If not, I'll pull the code in myself, but wanted to see if you wanted to do it first.

https://github.com/McInkay/ircd.js

**Comment by PaulFreund** [comment]
@McInkay I have long moved on and propose you merge the changes yourself, good Luck with the reboot ;)

**Comment by AlMcKinlay** [comment]
@PaulFreund I assumed as much. I actually noticed that this is GPLd which will cause me issues for what I want to do, so I've started a brand new project. What could go wrong? :-P

**Pull request closed without merging**
